title: <p align="center"> Rajashree Roy </p>
logo: /assets/img/Rajashree_photo.jpeg

description:   
  <p align="center">
  <a href="linkedin.com/in/rajashree-roy-3400b329/">LinkedIn</a> |
  <a href="https://github.com/rajashree3">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>


theme: jekyll-theme-minimal
