title: <p align="center"> Rajashree Roy </p>
logo: /assets/img/Rajashree_photo.jpeg

description:  
  <br>
  <br>
  <p align="center">
  <a href="linkedin.com/in/rajashree-roy-3400b329/">LinkedIn</a> |
  <a href="https://github.com/rajashree3">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark.
  Also handing the Big Data from real-time Ad call data.
  Worked win Deloitte at Big Data Analytics team.
  Working in Fintech domain for 7 years.
  <br>
  </p>


theme: jekyll-theme-minimal
